### ISSUE TITLE
Globalization and Localization

### ISSUE THREAD

**Issue by cmplstofB** [nlschn/semesterplanner#1]
Hello.
Is there any plan for globalization/localization for this package?
Currently, the strings in headline such as "Date", "Time" and so on is hardcoded in sourcecode, so, for example, it is difficult to inplement a system that switch output strings for each language using Babel.

**Comment by nlschn** [comment]
It was not actually planned, but I will surely look into how one can realize that (I'm fairly new to package-writing, so I will see what I can do).

**Comment by cmplstofB** [comment]
Thank you for your kindly reply!

You might want to refer to the packages that the LaTeX Project maintains officialy.
Since the contents to be translated in this package are not very complex, [layout package](https://github.com/latex3/latex2e/blob/master/required/tools/layout.dtx) is a good example to refer to, for example.

In combination with Babel package and so on, package can automatically determine document-wide language settings and apply it without specifing each package options.
However, this method will require complex implementation.

**Comment by nlschn** [comment]
Thank you for the reference!

**Comment by nlschn** [comment]
First three languages added with 9ef5795d65ac54cfb014f3565909feceb3c4e332!

**Comment by cmplstofB** [comment]
Thank you very much!
Could i pull a request (add another language) to you?

**Comment by nlschn** [comment]
Sure. There are only a few keys that have to be translated.

**Comment by rafaelpap** [comment]
I am not sure I am doing something wrong. The name of days in the timetable remains in english no matter the language.
![image](https://user-images.githubusercontent.com/45312334/103475177-30e51d00-4dab-11eb-89f7-1e8acb906cd0.png)

**Comment by nlschn** [comment]
I will look into that. Thanks.

It seems that I would have to change the schedule-package in order to translate the weekdays properly as they are hardcoded in the package.

**Comment by nlschn** [comment]
Should be fixed with e73dcfd844c1f5dec359e0a4ea0f36f00c7abee4
